on: [push]
jobs:
  build_analyze:
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.0
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Compile source
      run: cmake --build ${{github.workspace}}/build
    - name: Static analysis
      run: cmake --build ${{github.workspace}}/build --target analysis 
