on: [push]
jobs:
  build_analyze:
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B build/ . -DCMAKE_TOOLCHAIN_FILE=arm-toolchain.cmake
    - name: Compile source
      run: cmake --build build/
    - name: Static analysis
      run: cmake --build build/ --target analysis 
