name: CI

on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -B build/debug/ . --toolchain=arm-toolchain.cmake
      - name: Perform static analysis
        run: cmake --build build/debug/ --target analysis
  build:
    needs: static_analysis
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -B build/debug/ . --toolchain=arm-toolchain.cmake
      - name: Compile source
        run: cmake --build build/debug/
  unit_tests:
    needs: static_analysis
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -B build/tests/
      - name: Run all unit tests
        run: cmake --build build/tests/
  update_docs:
    needs: [build, unit_tests]
    runs-on: ubuntu-latest
    container: billisch/cortexm_dev:v1.3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Generate docs
        run: doxygen
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
          # force_orphan: true
